### ISSUE TITLE
Unify variable and variableSubstitution

### ISSUE THREAD

**Issue by piranna** [grncdr/js-shell-parse#9]
According to the spec both `variable` and `variableSubstitution` (with brackets) are the same thing, and in fact the first one is just sugar syntaxis for the brackets-one, so they should resolve to the same token.

Another alternative would be that `variableSubstitution` expresion would be calculated and in fact it makes sense, but this deviates from the spec and from how `bash` works, so I'm not fully sure if this "extension" should be done... :-/

**Comment by grncdr** [comment]
That's incorrect (unfortunately). Bash allows for a number of expressions inside a variableSubstitution that are not allowed on a bare variable. For example `${PATH/:/_}` expands to the value of `PATH` with all colons replaced with underscores. You can also remove strings from the front/end of the variable expansion, index array variables, and maybe a few other features I forgot about.

Furthermore, these expansions must happen at run-time, which essentially means a bash replacement must have a run-time interpreter for this sub-language.

**Comment by piranna** [comment]
I understood variable is equal to variableSubstitution when no expression
modifiers are used, maybe that code could be shared...
